ReliefApplications/oort-frontend

- libs/shared/src/lib/components/form-builder/form-builder.component.ts
- libs/shared/src/lib/services/form-builder/form-builder.service.ts
- libs/shared/src/lib/services/form-helper/form-helper.service.ts
- libs/ui/src/lib/icon/icon.component.html
- libs/ui/src/lib/icon/icon.component.ts
- libs/ui/src/lib/icon/icon.module.ts
The old tooltips took to long to show and were not consistent with the rest of the application's
> refactor: TooltipDirective on question tooltips

- apps/back-office/src/app/app-preview/pages/form/graphql/queries.ts
- apps/back-office/src/app/application/pages/form/graphql/queries.ts
- apps/back-office/src/app/dashboard/pages/form-answer/graphql/queries.ts
- apps/back-office/src/app/dashboard/pages/update-record/graphql/queries.ts
- apps/front-office/src/app/application/pages/form/form.component.ts
- apps/front-office/src/app/application/pages/form/graphql/queries.ts
- apps/web-widgets/src/app/widgets/form-widget/graphql/queries.ts
- libs/shared/src/i18n/en.json
- libs/shared/src/i18n/fr.json
- libs/shared/src/i18n/test.json
- libs/shared/src/lib/components/form-modal/form-modal.component.ts
- libs/shared/src/lib/components/form-modal/graphql/queries.ts
- libs/shared/src/lib/components/form/form.component.ts
- libs/shared/src/lib/services/form-builder/form-builder.service.ts
- libs/shared/src/lib/survey/components/field-search-table/field-search-table.component.html
- libs/shared/src/lib/survey/components/field-search-table/field-search-table.component.scss
- libs/shared/src/lib/survey/components/field-search-table/field-search-table.component.spec.ts
- libs/shared/src/lib/survey/components/field-search-table/field-search-table.component.ts
- libs/shared/src/lib/survey/components/field-search-table/graphql/queries.ts
- libs/shared/src/lib/survey/widgets/text-widget.ts
- libs/shared/src/lib/utils/update-queries.ts
This PR adds a feature that when enabled (in the question properties) displays a search table when on a form matching existing records filtered by that specific field (only text inputs)
- Please insert link to ticket: https://oortcloud.atlassian.net/browse/HIT-206?atlOrigin=eyJpIjoiMWMxZTk4ZGZkMmE5NDdiY2E2MDc1ZjFlNWQ1MzFmOGQiLCJwIjoiaiJ9
See below
> feat: search records when adding new ones

- apps/front-office/src/app/app.component.ts
Intercept button and anchor clicks and navigate with router
- Please insert link to ticket: https://oortcloud.atlassian.net/jira/software/projects/OORT/boards/5?selectedIssue=HIT-209
By creating a text widget with a link and clicking on it 
> feat: intercept click events and navigate using the router

- libs/shared/src/lib/components/form-builder/form-builder.component.ts
- libs/shared/src/lib/components/form-modal/form-modal.component.ts
- libs/shared/src/lib/components/form/form.component.ts
- libs/shared/src/lib/services/form-builder/form-builder.service.ts
- libs/shared/src/lib/survey/global-properties/others.ts
Adds fields on the survey to store a custom incremental ID shape and the padding
> feat: custom incremental ID

- libs/shared/src/lib/survey/functions/getCurrentYearAids.ts
- libs/shared/src/lib/survey/functions/index.ts
> feat: add getCurrentYearAids custom function

- libs/shared/src/lib/survey/components/resource.ts
> fix resource question filtering

- libs/shared/src/lib/survey/functions/index.ts
- libs/shared/src/lib/survey/functions/solidarites-demo/assets/link-data.ts
- libs/shared/src/lib/survey/functions/solidarites-demo/getLinkField.ts
> getLinkField function

- libs/shared/src/lib/survey/functions/solidarites-demo/assets/deprecation-data.ts
- libs/shared/src/lib/survey/functions/solidarites-demo/assets/link-data.ts
Change of static data for solidarite to fit our form format
> Changed solidarite static data

- libs/shared/src/lib/components/dashboard-filter/filter-builder-modal/filter-builder-modal.component.ts
> Users type question in dashboard filter

- apps/back-office/src/environments/environment.oort.dev.ts
- apps/back-office/src/environments/environment.oort.local.ts
- apps/back-office/src/environments/environment.ts
- apps/front-office/src/environments/environment.oort.dev.ts
- apps/front-office/src/environments/environment.oort.local.ts
- apps/front-office/src/environments/environment.ts
- apps/web-widgets/src/environments/environment.oort.dev.ts
- apps/web-widgets/src/environments/environment.oort.local.ts
- apps/web-widgets/src/environments/environment.ts
> HIT-373 Update environment configurations linked to id-dev, to work with new keycloak version

- apps/back-office/src/app/components/view-icon-selector/view-icon-selector.component.html
- apps/back-office/src/app/components/view-icon-selector/view-icon-selector.component.ts
- apps/back-office/src/app/components/view-settings-modal/view-settings-modal.component.html
- apps/back-office/src/app/components/view-settings-modal/view-settings-modal.component.ts
- libs/shared/src/lib/components/controls/icon-picker/icon-picker.component.html
- libs/shared/src/lib/components/controls/icon-picker/icon-picker.component.scss
- libs/shared/src/lib/components/controls/icon-picker/icon-picker.component.ts
> HIT-380 step & page icon can now be removed

- libs/shared/src/lib/components/ui/aggregation-builder/aggregation-builder.component.html
- libs/shared/src/lib/components/ui/aggregation-builder/aggregation-builder.component.scss
- libs/shared/src/lib/components/widgets/common/tab-actions/tab-actions.component.html
- libs/shared/src/lib/components/widgets/grid-settings/button-config/button-config.component.html
- libs/shared/src/lib/services/form-helper/form-helper.service.ts
- libs/ui/src/lib/dialog/dialog.component.html
- libs/ui/src/lib/icon/icon.component.html
> HIT-393 Fix position of icons

- libs/shared/src/lib/components/form-modal/form-modal.component.ts
- libs/shared/src/lib/components/form-modal/graphql/queries.ts
- libs/shared/src/lib/components/record-modal/graphql/queries.ts
- libs/shared/src/lib/components/record-modal/record-modal.component.ts
- libs/shared/src/lib/survey/components/resource.ts
- libs/shared/src/lib/survey/components/resources.ts
- libs/shared/src/lib/survey/graphql/queries.ts
- https://oortcloud.atlassian.net/browse/HIT-382
> HIT-382 Reduce amount of data queried by some elements

- libs/shared/src/i18n/en.json
- libs/shared/src/i18n/fr.json
- libs/shared/src/i18n/test.json
- libs/shared/src/lib/components/ui/aggregation-builder/aggregation-builder.component.html
- libs/shared/src/lib/components/ui/aggregation-builder/pipeline/pipeline.component.html
- libs/shared/src/lib/components/ui/aggregation-builder/pipeline/pipeline.component.ts
- libs/shared/src/lib/components/ui/aggregation-builder/pipeline/pipeline.module.ts
Feat:  updated custom aggregation to use monaco editor instead of plain text editor and changed the translation of french, to be “Personnalisé”.
[ticket](https://oortcloud.atlassian.net/browse/HIT-396)
> [HIT-396] Update custom aggregation

- apps/back-office/project.json
- libs/styles/src/lib/themes/unesco-mab/_variables.scss
modify project and variables to include unesco styling
https://oortcloud.atlassian.net/browse/HIT-418
> [HIT-418] adding primary and secondary variables

- apps/back-office/src/app/dashboard/pages/dashboard/dashboard.component.ts
> [HIT-421] template creation does not work

- apps/front-office/project.json
- libs/shared/src/lib/services/form-builder/form-builder.service.ts
- libs/shared/src/lib/services/form-helper/form-helper.service.ts
- package-lock.json
- package.json
ability to use markdown inside question names (usage of marked package) 
Repair a bug with empty nested resources questions 
apply mab styling to front-office
( * …
> [HIT-427] Repair history feature

- libs/shared/src/lib/components/form-modal/form-modal.component.html
- libs/shared/src/lib/components/form-modal/form-modal.component.ts
- libs/shared/src/lib/components/form-pages-layout/form-pages-layout.component.html
- libs/shared/src/lib/components/form-pages-layout/form-pages-layout.component.spec.ts
- libs/shared/src/lib/components/form-pages-layout/form-pages-layout.component.ts
- libs/shared/src/lib/components/form/form.component.html
- libs/shared/src/lib/components/form/form.module.ts
- libs/shared/src/lib/components/resource-modal/resource-modal.component.ts
> [hit-422] form layout on the left

- libs/shared/src/i18n/en.json
- libs/shared/src/i18n/fr.json
- libs/shared/src/i18n/test.json
- libs/shared/src/lib/components/form-modal/comments-popup/comments-popup.component.html
- libs/shared/src/lib/components/form-modal/comments-popup/comments-popup.component.spec.ts
- libs/shared/src/lib/components/form-modal/comments-popup/comments-popup.component.ts
- libs/shared/src/lib/components/form-modal/form-modal.component.html
- libs/shared/src/lib/components/form-modal/form-modal.component.scss
- libs/shared/src/lib/components/form-modal/form-modal.component.ts
- libs/shared/src/lib/components/form-modal/graphql/mutations.ts
- libs/shared/src/lib/components/form-modal/graphql/queries.ts
- libs/shared/src/lib/components/resource-modal/resource-modal.component.ts
- libs/shared/src/lib/models/comments.model.ts
- libs/shared/src/lib/survey/global-properties/others.ts
> [hit-429] comments can be added and viewed

- libs/shared/src/lib/components/record-modal/record-modal.component.html
- libs/shared/src/lib/components/record-modal/record-modal.component.ts
> [HIT-441] apply new layout to record modal

- apps/back-office/project.json
- libs/shared/src/i18n/en.json
- libs/shared/src/i18n/fr.json
- libs/shared/src/lib/components/form-modal/comments-popup/comments-popup.component.html
- libs/shared/src/lib/components/record-modal/record-modal.component.ts
- libs/shared/src/lib/services/download/download.service.ts
- libs/shared/src/lib/services/form-builder/form-builder.service.ts
- libs/shared/src/lib/survey/components/matrices.ts
- libs/shared/src/lib/survey/creator.ts
- libs/shared/src/lib/survey/global-properties/others.ts
- libs/shared/src/lib/survey/progress-bar/progress-bar.component.ts
- libs/ui/src/lib/snackbar/snackbar.component.ts
- libs/ui/src/lib/snackbar/snackbar.service.ts
> [Hit-434] ability to upload big documents

- libs/shared/src/lib/components/widgets/form/form-widget.component.ts
- libs/shared/src/lib/services/form-builder/form-builder.service.ts
- libs/shared/src/lib/survey/global-properties/others.ts
Adds button to dynamic panel/matrix question to import xlsx files. If the column names match, the imported rows will be displayed in the question.
- Link to ticket: https://www.notion.so/Allow-uploading-csv-and-xlsx-on-dynamic-panels-19ad463fd8c480eaa5e9cd2f7fc09d5b?pvs=4
- Please insert link to back-end branch if any https://github.com/ReliefApplications/oort-backend/pull/78
See bellow
https://github.com/user-attachments/assets/10d50f56-c37a-4f72-be05-d8742a812949
( * == Mandatory )
> MAB-238 upload xslx to dynamic panel 

- libs/shared/src/i18n/en.json
- libs/shared/src/i18n/fr.json
- libs/shared/src/i18n/test.json
- libs/shared/src/lib/components/form/form.component.html
- libs/shared/src/lib/components/form/form.component.ts
- libs/shared/src/lib/components/ui/core-grid/grid/grid.component.html
- libs/shared/src/lib/components/widgets/form-settings/form-settings.forms.ts
- libs/shared/src/lib/components/widgets/form-settings/tab-main/tab-main.component.html
- libs/shared/src/lib/components/widgets/form-settings/tab-main/tab-main.component.ts
- libs/shared/src/lib/components/widgets/form-settings/tab-map-question-state/tab-map-question-state.component.html
- libs/shared/src/lib/components/widgets/form/form-widget.component.html
- libs/shared/src/lib/components/widgets/form/form-widget.component.ts
- libs/shared/src/lib/components/widgets/form/form-widget.module.ts
- libs/shared/src/lib/services/dashboard/dashboard.service.ts
- libs/shared/src/lib/services/form-builder/form-builder.service.ts
- libs/shared/src/lib/survey/progress-bar/progress-bar.component.html
* Adds option to update record from form widget
* Adds a couple variables to be used inside a form` __FOCUSED__.name` and `__FOCUSED__.title`, which contains, respectively, the name and title of the focused question
* Minor UI changes on the form widget settings
* Loads query params into dashboard state if the names match
- Please insert link to ticket: https://www.notion.so/Enhance-workflow-capabilities-from-dashboard-b1df7b99fe484cb49deda529d31cdbed?pvs=4
All the added features were used for the [comments dashboard](https://mab.unesco.oortcloud.tech/admin/applications/675c9597851e937cd9b1fdee/dashboard/67aa57a8179bb525b32dd49e?id=6790849ec802f229e91295b8):
* Both forms are using the update record feature
* The form on the left is using the …
> MAB-224: improvements on form widget

- libs/shared/src/lib/components/form-modal/form-modal.component.ts
- libs/shared/src/lib/components/form/form.component.html
- libs/shared/src/lib/components/form/form.component.ts
- libs/shared/src/lib/services/form-builder/form-builder.service.ts
- libs/shared/src/lib/services/form-helper/form-helper.service.ts
- libs/shared/src/lib/survey/components/resource.ts
- libs/shared/src/lib/survey/components/resources.ts
- libs/shared/src/lib/survey/components/utils.ts
- libs/shared/src/lib/survey/global-properties/others.ts
- libs/shared/src/lib/survey/render-global-properties.ts
- libs/shared/src/lib/survey/widgets/tagbox-widget.ts
- libs/shared/src/lib/survey/widgets/text-widget.ts
Improve form performance by enabling lazy loading + refactoring survey subscribers
- Please insert link to ticket https://www.notion.so/Improve-form-performance-1a1d463fd8c48000ac41d66fb5349729?pvs=4
Check ticket description
( * == Mandatory )
> refactor: improve form performance

- libs/shared/src/lib/components/form-modal/form-modal.component.html
- libs/shared/src/lib/components/form-pages-layout/form-pages-layout.component.html
- libs/shared/src/lib/components/form-pages-layout/form-pages-layout.component.ts
- libs/shared/src/lib/components/form/form.component.html
- libs/shared/src/lib/components/record-modal/record-modal.component.html
> Ability to collapse pages menu

- libs/shared/src/i18n/en.json
- libs/shared/src/i18n/fr.json
- libs/shared/src/i18n/test.json
- libs/shared/src/lib/components/form-modal/comments-popup/comments-popup.component.html
- libs/shared/src/lib/components/form-modal/comments-popup/comments-popup.component.ts
- libs/shared/src/lib/components/form-modal/form-modal.component.html
- libs/shared/src/lib/components/form-modal/form-modal.component.ts
- libs/shared/src/lib/components/form-pages-layout/form-pages-layout.component.html
- libs/shared/src/lib/components/form/form.component.html
- libs/shared/src/lib/components/form/form.component.ts
- libs/shared/src/lib/components/form/form.module.ts
- libs/shared/src/lib/components/resource-modal/resource-modal.component.ts
- libs/shared/src/lib/services/download/download.service.ts
- libs/shared/src/lib/services/form-builder/form-builder.service.ts
- libs/shared/src/lib/services/form-helper/form-helper.service.ts
- libs/shared/src/lib/survey/components/utils.ts
- libs/shared/src/lib/survey/global-properties/others.ts
- libs/ui/src/lib/fixed-wrapper/fixed-wrapper.component.html
> Autosave records

- libs/shared/src/i18n/en.json
- libs/shared/src/i18n/fr.json
- libs/shared/src/i18n/test.json
- libs/shared/src/lib/components/ui/core-grid/core-grid.component.ts
- libs/shared/src/lib/components/ui/core-grid/grid/grid.component.html
- libs/shared/src/lib/components/ui/core-grid/grid/grid.component.ts
- libs/shared/src/lib/components/widgets/common/tab-actions/tab-actions.component.ts
- libs/shared/src/lib/components/widgets/grid-settings/button-config/button-config.component.html
- libs/shared/src/lib/components/widgets/grid-settings/button-config/button-config.component.ts
- libs/shared/src/lib/components/widgets/grid-settings/button-config/button-config.module.ts
- libs/shared/src/lib/components/widgets/grid-settings/grid-settings.forms.ts
- libs/shared/src/lib/components/widgets/grid/grid.component.html
- libs/shared/src/lib/components/widgets/grid/grid.component.ts
- libs/shared/src/lib/services/application/application.service.ts
This PR refactors the quick action buttons
- Please insert link to ticket https://www.notion.so/Quick-action-buttons-1acd463fd8c48074b20bea74e5895b02?pvs=4
> MAB-246 refactor: quick grid actions 

- libs/shared/src/i18n/en.json
- libs/shared/src/i18n/fr.json
- libs/shared/src/i18n/test.json
- libs/shared/src/lib/components/ui/core-grid/grid/grid.component.html
- libs/shared/src/lib/components/ui/core-grid/grid/grid.component.ts
- libs/shared/src/lib/components/widgets/grid-settings/button-config/button-config.component.html
- libs/shared/src/lib/components/widgets/grid-settings/button-config/button-config.component.ts
- libs/shared/src/lib/components/widgets/grid-settings/button-config/button-config.module.ts
- libs/shared/src/lib/components/widgets/grid-settings/grid-settings.forms.ts
- libs/shared/src/lib/utils/parser/utils.ts
This PR removes the displayIfTruthy property and adds a more complex filter in it's place to determine if the row will have the button displayed in it 
- Please insert link to ticket https://www.notion.so/Enhance-workflow-capabilities-from-dashboard-b1df7b99fe484cb49deda529d31cdbed?pvs=4
By setting up the grids on the submission dashboard on MAB
( * == Mandatory )
> HIT-224 add filter to determine if quick action button will be displayed on row level

- libs/shared/src/lib/components/form/form.component.html
- libs/shared/src/lib/components/form/form.component.ts
> omitted fields not autosaved anymore + fix some ui for form widgets

- libs/shared/src/lib/components/form-builder/form-builder.component.scss
- libs/shared/src/lib/components/form-builder/form-builder.component.ts
- libs/shared/src/lib/services/form-builder/form-builder.service.ts
- libs/shared/src/lib/survey/functions/index.ts
- libs/shared/src/lib/survey/functions/onComplete.ts
- libs/shared/src/lib/survey/functions/once.ts
add onComplete method, 
correct once method, 
change form edition to be by page (long forms would be a struggle without it)
( * == Mandatory ) …
> More form features

- libs/shared/src/lib/services/form-helper/form-helper.service.ts
- libs/shared/src/lib/survey/components/resource.ts
- libs/shared/src/lib/survey/components/resources.ts
- libs/shared/src/lib/survey/functions/index.ts
- libs/shared/src/lib/survey/functions/mab/getPreviouslyReported.ts
- libs/shared/src/lib/survey/functions/substr.ts
Refactor form helper logic and add new survey functions - Improved logic for handling panel headers and upload buttons in FormHelpersService. - Adjusted header styles in survey components for better alignment and spacing. - Updated `updateGrid` function to accept optional values in resources.ts. - Added new custom functions: `getPreviouslyReported` and `substr`. - Registered new functions in the survey functions
Please …
> add a couple new custom functions

- libs/shared/src/i18n/en.json
- libs/shared/src/i18n/fr.json
- libs/shared/src/i18n/test.json
- libs/shared/src/lib/components/form/form.component.ts
- libs/shared/src/lib/components/widgets/form-settings/form-settings.forms.ts
- libs/shared/src/lib/components/widgets/form-settings/tab-main/tab-main.component.html
- libs/shared/src/lib/components/widgets/form/form-widget.component.ts
- libs/shared/src/lib/services/dom/dom.service.ts
- libs/shared/src/lib/services/form-builder/form-builder.service.ts
- libs/shared/src/lib/survey/widgets/dropdown-widget.ts
> [HIT-450] allow form widget creating new record from loaded record

- libs/shared/src/i18n/en.json
- libs/shared/src/i18n/fr.json
- libs/shared/src/i18n/test.json
- libs/shared/src/lib/components/layout/layout.component.html
- libs/shared/src/lib/components/layout/layout.component.ts
- libs/shared/src/lib/models/notification.model.ts
- libs/shared/src/lib/services/notification/graphql/mutations.ts
- libs/shared/src/lib/services/notification/notification.service.ts
> improve mark as seen and loading functionality

- libs/shared/src/i18n/en.json
- libs/shared/src/i18n/fr.json
- libs/shared/src/i18n/test.json
- libs/shared/src/lib/components/layout/layout.component.html
- libs/shared/src/lib/components/ui/core-grid/grid/grid.component.ts
- libs/shared/src/lib/components/widgets/grid-settings/grid-settings.component.html
> Small bug repairs

- libs/shared/src/lib/survey/global-properties/others.ts
- libs/shared/src/lib/survey/widgets/dropdown-widget.ts
Fix required logic, improve dropdown updates
- Ensure isRequired and `requiredIf` are correctly restored to their original states during logic execution.
- `createDropdownInstance` now returns `ComponentRef` for better dropdown component management.
- Explicitly trigger change detection on dropdown value changes to ensure UI updates.
https://github.com/user-attachments/assets/e015f047-9cdd-4d86-8194-035b9322c0eb
> fix: survey dropdowns not retainning values

- apps/back-office/src/environments/environment.ts
- libs/shared/src/lib/survey/global-properties/others.ts
Enable conditional expand/collapse of panels in forms based on expressions, similar to conditional visibility.
> HIT-459: Implement conditional panel expand feature

- libs/shared/src/lib/services/context/context.service.ts
- libs/shared/src/lib/services/form-builder/form-builder.service.ts
- libs/shared/src/lib/survey/global-properties/others.ts
1. Changed the logic for the previous serializer because it was causing the issue with the missing asterisks 
2. implement handler to manage skipping required questions using onValidateQuestion native survey method 
- https://www.notion.so/Try-to-improve-skipRequiredValidation-of-forms-so-it-continues-to-display-questions-as-mandatory-23ed463fd8c480359027e81e43a4ede4
- https://surveyjs.answerdesk.io/ticket/details/t21714/validate-a-custom-question-with-onvalidatequestion-event?_gl=1*1c5f7ae*_gcl_au*MjA2MjczOTAxNS4xNzUwMTY2MDIw*_ga*MzE0OTQ5NDI5LjE3NTAxNjYwMjA.*_ga_SM5CHDPRR8*czE3NTM5MjQyNTQkbzUkZzEkdDE3NTM5MjQyOTIkajIyJGwxJGg0OTA0MzA2MDY.
- https://plnkr.co/edit/ourOqdhh6rbmGzcX?preview
Please describe the tests that you ran to verify your …
> [MAB-316] improve skip validation service

- libs/shared/src/lib/components/users/add-user/add-user.component.ts
- libs/shared/src/lib/survey/components/users-dropdown/users-dropdown.component.html
- libs/shared/src/lib/survey/components/users-dropdown/users-dropdown.component.ts
- libs/ui/src/lib/graphql-select/graphql-select.component.ts
1. Limit the amount of character to be typed before trigger a user's search request
2. Limit the amount of user to be requested to 5
3. Filter the user's string typed removing '@' character to search by email only and not domains
- https://www.notion.so/Limit-search-on-users-in-users-field-240d463fd8c48027b0fbe63bbfc4a796
> [MAB-329] limit users and what the user can type in user search field

- libs/shared/src/lib/components/ui/map/map.component.ts
> fix: add update unesco basemap so it always displays as satelite

- libs/shared/src/lib/components/dashboard-filter/dashboard-filter.component.ts
- libs/shared/src/lib/components/dashboard-filter/filter-builder-modal/filter-builder-modal.component.ts
- libs/shared/src/lib/components/form-builder/form-builder.component.ts
- libs/shared/src/lib/directives/async-monaco-editor/async-monaco-editor.directive.ts
- libs/shared/src/lib/directives/async-monaco-editor/public-api.ts
- libs/shared/src/lib/services/form-builder/form-builder.service.ts
- libs/shared/src/lib/survey/components/query-editor/public-api.ts
- libs/shared/src/lib/survey/components/query-editor/query-editor.component.html
- libs/shared/src/lib/survey/components/query-editor/query-editor.component.spec.ts
- libs/shared/src/lib/survey/components/query-editor/query-editor.component.ts
- libs/shared/src/lib/survey/components/query-editor/query-editor.model.ts
- libs/shared/src/lib/survey/components/utils/components.enum.ts
- libs/shared/src/lib/survey/global-properties/choices-by-graphql.ts
- libs/shared/src/lib/survey/global-properties/graphql-variables.ts
- libs/shared/src/lib/survey/global-properties/reference-data.ts
- libs/shared/src/lib/survey/init.ts
- libs/shared/src/lib/survey/render-global-properties.ts
> MAB-431 Add GQl choices in surveyjs
